services:
  gtp-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - DB_HOST=host.docker.internal
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=password
      - DB_DATABASE=goods_to_person
      - DB_SSL=false
      - JWT_SECRET=jwtConfig.secret
      - WMS_WAREHOUSE_NAME=WH_001
      - WMS_WAREHOUSE_AUTH_KEY=test
      - WMS_BASE_URL=http://host.docker.internal:9000
      - BOT_API_KEY=api_key
